name: echalan
description: Mobile app for echalan service
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
 
  intl: ^0.19.0
  dartz: ^0.10.1
  dio: ^5.5.1
  shared_preferences: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.16
  freezed_annotation: ^2.4.1
  freezed: ^2.3.5
  formz: ^0.7.0
  get_it: ^8.0.3
  flutter_gen: any
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.10
  qr_code_scanner: ^1.0.1
  fresh_dio: ^0.4.1
  injectable: ^2.3.2
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.8
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svgs/

fonts:
    - family: PublicSans-Regular
      fonts:
        - asset: fonts/PublicSans-Regular.ttf
    - family: PublicSans-Medium
      fonts:
        - asset: fonts/PublicSans-Medium.ttf
    - family: PublicSans-SemiBold
      fonts:
        - asset: fonts/PublicSans-SemiBold.ttf
    - family: PublicSans-Bold
      fonts:
        - asset: fonts/PublicSans-Bold.ttf

